@extends('layout')
@section('title','Ringkasan')
@section('content')
<div class="page-heading"><div><span class="eyebrow">SEMUANYA DALAM SATU RUANG</span><h1>Selamat datang, {{ explode(' ',auth()->user()->name)[0] }} <span class="greeting-spark">✳</span></h1><p>Berikut kabar toko Anda hari ini. Mari buat hari yang produktif.</p></div><a href="/manage/sales/create" class="button">＋ Catat penjualan</a></div>
<div class="stats-grid">
<div class="stat-card"><span class="stat-icon mint">↗</span><p>{{ auth()->user()->isOwner()?'Omzet penjualan selesai':'Pemasukan Hari Ini' }}</p><h2>@rupiah($revenue)</h2><small>{{ auth()->user()->isOwner()?'Akumulasi seluruh transaksi selesai':'Pembayaran diterima hari ini' }}</small></div>
<div class="stat-card"><span class="stat-icon peach">▣</span><p>Pesanan perlu diproses</p><h2>{{ $pending }} <span>pesanan</span></h2><a href="/manage/orders?status=pending">Kelola pesanan →</a></div>
<div class="stat-card"><span class="stat-icon lilac">◇</span><p>Total produk</p><h2>{{ $productCount }} <span>produk</span></h2><small>Seluruh produk dalam katalog</small></div>
<div class="stat-card"><span class="stat-icon sand">▤</span><p>Stok perlu perhatian</p><h2>{{ $lowCount }} <span>produk</span></h2><a href="/manage/stock">Periksa persediaan →</a></div>
</div>
<div class="dashboard-banner"><span class="banner-symbol">✳</span><div><h3>Toko tertata, usaha melangkah.</h3><p>Catat setiap barang masuk dan penjualan agar stok selalu sesuai.</p></div><a class="button secondary" href="/manage/stock">Kelola stok →</a></div>
<div class="dashboard-columns"><section class="panel"><div class="panel-heading"><div><h2>Pesanan terbaru</h2><p class="muted">Pantau aktivitas belanja pelanggan.</p></div><a href="/manage/orders" class="text-link">Lihat semua ↗</a></div><div class="table-wrap"><table><thead><tr><th>Pesanan / pelanggan</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>@forelse($orders as $order)<tr><td><strong>{{ $order->number }}</strong><small>{{ $order->customer_name }}</small></td><td>@rupiah($order->total)</td><td>@include('orders.status',['status'=>$order->status])</td><td><a href="/orders/{{ $order->id }}" aria-label="Lihat pesanan {{ $order->number }}">↗</a></td></tr>@empty<tr><td colspan="4" class="empty">Belum ada pesanan. Pesanan baru akan tampil di sini.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><div class="panel-heading"><div><h2>Stok menipis</h2><p class="muted">Saatnya mengisi kembali.</p></div><span class="badge warning">{{ $lowCount }}</span></div>@forelse($lowStock as $p)<a href="/manage/products/{{ $p->id }}/edit" class="low-stock-row"><span class="mini-product tone-{{ $p->id%4 }}"><img src="{{ $p->image_url }}" alt=""></span><div><strong>{{ $p->name }}</strong><small>{{ $p->sku }}</small></div><span class="stock-count">{{ $p->stock }}<small>tersisa</small></span></a>@empty<div class="empty">✓ Seluruh stok dalam batas aman.</div>@endforelse<a href="/manage/stock" class="button secondary full">Lihat semua stok →</a></section></div>
<div class="dashboard-columns"><section class="panel"><div class="panel-heading"><h2>Pergerakan stok terakhir</h2><a href="/manage/stock" class="text-link">Riwayat →</a></div>@forelse($movements as $m)<div class="activity-row"><span class="activity-dot {{ $m->quantity<0?'out':'' }}">{{ $m->quantity>0?'↙':'↗' }}</span><div><strong>{{ $m->product->name }}</strong><small>{{ $m->reference }} · {{ $m->created_at->format('d M, H:i') }}</small></div><b class="{{ $m->quantity>0?'positive':'' }}">{{ $m->quantity>0?'+':'' }}{{ $m->quantity }}</b></div>@empty<p class="empty">Pergerakan barang akan tercatat otomatis.</p>@endforelse</section><section class="panel quiet-panel"><span class="eyebrow">{{ auth()->user()->isOwner()?'KHUSUS OWNER':'RUANG KONTEN' }}</span>@can('owner')<h2>Laba kotor penjualan</h2>@if(\App\Models\OrderItem::where('cost_confirmed',false)->whereHas('order',fn($q)=>$q->where('status','completed'))->exists())<p class="badge warning">Modal belum lengkap — keuntungan sementara</p>@endif<div class="large-number">@rupiah($profit)</div><p>Omzet transaksi selesai dikurangi modal barang terjual. Belum dikurangi biaya operasional.</p><a href="/manage/reports" class="text-link">Buka laporan lengkap ↗</a>@else<h2>Bagikan kabar terbaru.</h2><p>Tulis berita, perbarui cerita, dan kelola akun penulis dari satu tempat.</p><a href="/manage/articles" class="text-link">Kelola berita ↗</a>@endcan</section></div>
@endsection

