@extends('layout')
@section('title','Pengeluaran')
@section('content')
<div class="page-heading"><div><span class="eyebrow">{{ auth()->user()->isOwner()?'PENGELUARAN TOKO':'PENGELUARAN YANG ANDA CATAT' }}</span><h1>Pengeluaran toko</h1><p>Pembayaran supplier, operasional, dan pengembalian DP dalam satu menu.</p></div><a class="button" href="/manage/expenses/create">＋ Catat pengeluaran</a></div>
<form class="filter-bar"><label class="report-search-field">Cari pengeluaran<input type="search" name="q" value="{{ request('q') }}" maxlength="150" placeholder="EXP, invoice, penerima, atau catatan"></label><label>Dari tanggal<input type="date" name="from" value="{{ $from }}" required></label><label>Sampai tanggal<input type="date" name="to" value="{{ $to }}" required></label><label>Kategori<select name="category"><option value="">Semua kategori</option>@foreach(App\Models\ExpenseCategory::labels()+['refund'=>'Pengembalian DP'] as $key=>$label)<option value="{{ $key }}" @selected($category===$key)>{{ $label }}</option>@endforeach</select></label><button>Tampilkan</button></form>
<div class="stats-grid">@foreach($totals as $label=>$amount)<div class="stat-card"><p>{{ $label }}</p><h2>@rupiah($amount)</h2></div>@endforeach<div class="stat-card"><p>Total pengeluaran periode</p><h2>@rupiah(array_sum($totals))</h2><small>Seluruh kategori sesuai pencarian, termasuk pengembalian DP satu kali.</small></div></div>
<section class="panel table-wrap"><h2>Pengeluaran yang dicatat</h2><table><thead><tr><th>Tanggal</th><th>Kategori / penerima</th><th>Jumlah / metode</th><th>Perubahan stok</th><th>Catatan / petugas</th></tr></thead><tbody>@forelse($expenses as $expense)<tr><td>{{ $expense->spent_on->format('d M Y') }}<small>EXP-{{ $expense->id }}</small></td><td>{{ App\Models\ExpenseCategory::labels()[$expense->category] }}<small>{{ $expense->recipient }} @if($expense->supplier) · {{ $expense->supplier->name }}@endif</small></td><td>@rupiah($expense->amount)<small>{{ $expense->method==='cash'?'Tunai':'Transfer' }}</small></td><td>@if($expense->stock_change){{ $expense->stock_change>0?'+':'' }}{{ $expense->stock_change }} · {{ $expense->product->name }}@else Tidak mengubah stok @endif</td><td>{{ $expense->note }}<small>{{ $expense->user->name }}</small></td></tr>@empty<tr><td colspan="5">Belum ada pengeluaran pada pilihan ini.</td></tr>@endforelse</tbody></table>@include('components.pager',['paginator'=>$expenses])</section>
<section class="panel table-wrap"><h2>Pengembalian DP — otomatis</h2><p>Diambil dari pembatalan transaksi. Jangan dicatat ulang sebagai pengeluaran manual.</p><table><thead><tr><th>Waktu</th><th>Transaksi / pelanggan</th><th>Dikembalikan</th><th>Metode / alasan</th></tr></thead><tbody>@forelse($refunds as $refund)<tr><td>{{ $refund->received_at->format('d M Y H:i') }}</td><td><a href="/orders/{{ $refund->order_id }}">{{ $refund->order->number }}</a><small>{{ $refund->order->customer_name }}</small></td><td>@rupiah(-$refund->amount)</td><td>{{ $refund->method==='cash'?'Tunai':'Transfer' }}<small>{{ $refund->note }}</small></td></tr>@empty<tr><td colspan="4">Belum ada pengembalian DP pada pilihan ini.</td></tr>@endforelse</tbody></table>@include('components.pager',['paginator'=>$refunds])</section>
@endsection
