@extends('layout')
@section('title','Laporan')
@section('content')
<div class="page-heading"><div><span class="eyebrow">ANGKA YANG BERCERITA</span><h1>Laporan toko</h1><p>Omzet dihitung sekali saat transaksi selesai. Pembayaran DP dan pelunasan dicatat berdasarkan tanggal uang diterima.</p></div><a class="button secondary" href="{{ request()->fullUrlWithQuery(['export'=>1,'from'=>$from,'to'=>$to]) }}">↓ Ekspor CSV</a></div>
<form class="filter-bar"><label class="report-search-field">Cari transaksi<input type="search" name="q" value="{{ request('q') }}" maxlength="150" placeholder="Invoice, pelanggan, atau pengerjaan"></label><label>Dari tanggal<input type="date" name="from" value="{{ $from }}" required></label><label>Sampai tanggal<input type="date" name="to" value="{{ $to }}" required></label><button>Tampilkan laporan</button></form>
<div class="stats-grid"><div class="stat-card"><p>Omzet periode ini</p><h2>@rupiah($revenue)</h2><small>{{ $count }} transaksi selesai</small></div><div class="stat-card"><p>Barang terjual</p><h2>{{ $quantity }} <span>unit</span></h2><small>Dalam periode terpilih</small></div><div class="stat-card"><p>Stok saat ini</p><h2>{{ $stock }} <span>unit</span></h2><small>Seluruh produk</small></div>@can('owner')<div class="stat-card"><p>Laba kotor</p><h2>@rupiah($profit)</h2><small>Omzet − modal barang terjual</small></div>@endcan</div>
@can('owner')<div class="owner-info"><strong>Khusus Owner</strong><p>Pengeluaran manual periode ini: @rupiah($expenses) · Arus kas bersih periode: @rupiah($incoming-$refunds-$expenses)</p><small>Arus kas bukan laba atau saldo kas akhir; belum memasukkan saldo awal. Pembelian stok tidak dikurangkan lagi dari laba kotor, karena modal barang sudah dihitung saat penjualan.</small><p>Pembayaran masuk periode ini (termasuk DP): @rupiah($incoming) · Pengembalian: @rupiah($refunds) · Pemasukan bersih: @rupiah($incoming-$refunds)</p><p>Sisa tagihan seluruh transaksi langsung: @rupiah($receivables)</p><p>Omzet produk: @rupiah($productRevenue) · Omzet jasa: @rupiah($serviceRevenue)</p>@if($missingCost)<p class="badge warning">Modal belum lengkap: {{ $missingCost }} item transaksi. Laba kotor masih sementara.</p>@endif<p>Modal barang terjual: @rupiah($cost) · Nilai persediaan saat ini: @rupiah($stockValue)</p><small>Modal diisi manual oleh Superadmin dan mengikuti koreksi transaksi yang tercatat. Laba kotor belum dikurangi biaya operasional dan pajak.</small></div>@endcan
<section class="panel table-wrap"><h2>Transaksi selesai</h2><p class="muted">Pencarian menyaring daftar transaksi dan ekspor CSV. Ringkasan angka tetap untuk seluruh periode terpilih.</p><table><thead><tr><th>Pesanan</th><th>Tanggal selesai</th><th>Pelanggan</th><th>Total</th></tr></thead><tbody>@forelse($orders as $o)<tr><td><a href="/orders/{{ $o->id }}">{{ $o->number }} ↗</a></td><td>{{ $o->completed_at->format('d M Y') }}</td><td>{{ $o->customer_name }}</td><td>@rupiah($o->total)</td></tr>@empty<tr><td colspan="4" class="empty">Belum ada transaksi selesai pada periode ini.</td></tr>@endforelse</tbody></table>@include('components.pager',['paginator'=>$orders])</section>
@endsection

