@extends('layout')
@section('title','Stok barang')
@section('content')
<div class="page-heading"><div><span class="eyebrow">INVENTORI</span><h1>Stok barang</h1><p>Setiap perubahan tercatat, setiap barang terpantau.</p></div><a class="button" href="/manage/products">Kelola produk</a></div>
<form class="filter-bar stock-search" action="/manage/stock" method="get" role="search"><label class="search-field">Cari produk atau SKU<input type="search" name="q" value="{{ $search }}" placeholder="Contoh: Laptop atau CC-LP-001" maxlength="100"></label>@if($sort)<input type="hidden" name="sort" value="{{ $sort }}">@endif<button type="submit">Cari stok</button>@if($search!=='')<a class="text-link" href="/manage/stock{{ $sort?'?sort='.$sort:'' }}">Hapus pencarian</a>@endif</form>
<section class="panel table-wrap"><h2>Persediaan saat ini</h2>@if($search!=='')<p class="muted">{{ $products->total() }} produk ditemukan untuk “{{ $search }}”.</p>@endif<table><thead><tr><th>Produk</th><th>SKU</th><th aria-sort="{{ $sort === 'asc' ? 'ascending' : ($sort === 'desc' ? 'descending' : 'none') }}"><div class="stock-sort">Stok fisik <a class="stock-sort-button {{ $sort === 'asc' ? 'is-active' : '' }}" href="{{ request()->fullUrlWithQuery(['sort'=>'asc']) }}" @if($sort === 'asc')aria-current="true"@endif title="Urutkan stok paling sedikit" aria-label="Urutkan stok paling sedikit">↑</a><a class="stock-sort-button {{ $sort === 'desc' ? 'is-active' : '' }}" href="{{ request()->fullUrlWithQuery(['sort'=>'desc']) }}" @if($sort === 'desc')aria-current="true"@endif title="Urutkan stok paling banyak" aria-label="Urutkan stok paling banyak">↓</a></div></th><th>Dipesan</th><th>Tersedia</th><th>Batas minimum</th><th>Kondisi</th><th>Aksi</th></tr></thead><tbody>@forelse($products as $p)<tr><td>{{ $p->name }}</td><td>{{ $p->sku }}</td><td><strong>{{ $p->stock }}</strong></td><td>{{ $p->reserved_stock }}</td><td>{{ $p->available_stock }}</td><td>{{ $p->min_stock }}</td><td><span class="badge {{ $p->stock<=$p->min_stock?'warning':'' }}">{{ $p->stock<=$p->min_stock?'Perlu diisi':'Aman' }}</span></td><td><div class="stock-row-actions">@if($p->active)<a href="/products/{{ $p->id }}" target="_blank" rel="noopener" aria-label="Lihat halaman produk {{ $p->name }}">Lihat produk ↗</a>@endif<a class="stock-sort-button" href="/manage/stock/{{ $p->id }}/edit" aria-label="Edit stok {{ $p->name }}">✎ Edit</a></div></td></tr>@empty<tr><td colspan="8" class="empty">{{ $search!==''?'Tidak ada produk yang cocok.':'Belum ada produk.' }}</td></tr>@endforelse</tbody></table>@include('components.pager',['paginator'=>$products])</section>
<section class="panel table-wrap"><h2>Riwayat pergerakan</h2><table><thead><tr><th>Waktu</th><th>Produk</th><th>Perubahan</th><th>Saldo</th><th>Referensi / catatan</th><th>Petugas</th></tr></thead><tbody>@forelse($movements as $m)<tr><td>{{ $m->created_at->format('d M Y H:i') }}</td><td>{{ $m->product->name }}</td><td class="{{ $m->quantity>0?'positive':'warning-text' }}">{{ $m->quantity>0?'+':'' }}{{ $m->quantity }}</td><td>{{ $m->balance }}</td><td>{{ $m->reference }}<small>{{ $m->note }}</small></td><td>{{ $m->user->name }}</td></tr>@empty<tr><td colspan="6" class="empty">Belum ada pergerakan stok.</td></tr>@endforelse</tbody></table>@include('components.pager',['paginator'=>$movements])</section>
@endsection

