@extends('layout')
@section('title',auth()->user()->isOwner()?'Pengguna':'Akun penulis')
@section('content')
<div class="page-heading"><div><span class="eyebrow">TIM & PELANGGAN</span><h1>{{ auth()->user()->isOwner()?'Pengguna':'Akun penulis' }}</h1><p>Kelola identitas dan akses pengguna website.</p></div></div>
@php($roles=auth()->user()->isOwner()?['customer'=>'Customer','writer'=>'Penulis berita','admin'=>'Admin','owner'=>'Superadmin / Owner']:['writer'=>'Penulis berita'])
<details class="panel"><summary>＋ Tambah akun</summary><form class="form-grid" method="post" action="/manage/users">@csrf<label>Nama<input name="name" required maxlength="100"></label><label>Email<input name="email" type="email" required></label><label>Peran<select name="role">@foreach($roles as $k=>$v)<option value="{{ $k }}">{{ $v }}</option>@endforeach</select></label><label>Kata sandi awal<input name="password" type="password" required minlength="10" autocomplete="new-password"><small>Minimal 10 karakter.</small></label><div><button>Buat akun</button></div></form></details>
<div class="panel">@forelse($users as $u)<details class="user-row"><summary><span class="avatar">{{ mb_substr($u->name,0,1) }}</span><span><strong>{{ $u->name }}</strong><small>{{ $u->email }}</small></span><span class="badge neutral">{{ $roles[$u->role]??$u->role }}</span><span class="text-link">Edit</span></summary><form class="form-grid" action="/manage/users/{{ $u->id }}" method="post">@csrf @method('PUT')<label>Nama<input name="name" value="{{ $u->name }}" required></label><label>Email<input type="email" name="email" value="{{ $u->email }}" required></label><label>Peran<select name="role">@foreach($roles as $k=>$v)<option value="{{ $k }}" @selected($u->role===$k)>{{ $v }}</option>@endforeach</select></label><label>Kata sandi baru (opsional)<input name="password" type="password" minlength="10" autocomplete="new-password"></label><button>Simpan perubahan</button></form></details>@empty<p class="empty">Belum ada akun yang ditampilkan.</p>@endforelse @include('components.pager',['paginator'=>$users])</div>
@endsection

