@extends('layout')
@section('title',$staff?'Pesanan & penjualan':'Pesanan saya')
@section('content')
<div class="page-heading"><div><span class="eyebrow">{{ $staff?'AKTIVITAS TOKO':'BELANJA ANDA' }}</span><h1>{{ $staff?'Pesanan & penjualan':'Pesanan saya' }}</h1><p>{{ $staff?'Kelola pesanan online dan transaksi langsung.':'Pantau perjalanan pesanan Anda di sini.' }}</p></div>@if($staff)<a href="/manage/sales/create" class="button">＋ Penjualan langsung</a>@else<a href="/products" class="button">Belanja lagi ↗</a>@endif</div>
@if($staff)<form class="filter-bar" action="/manage/orders" method="get" role="search"><label class="order-search-field">Cari pesanan atau penjualan<input type="search" name="q" value="{{ $search }}" maxlength="100" placeholder="Nomor, pelanggan, telepon, barang atau jasa"></label><label>Status<select name="status"><option value="">Semua status</option>@foreach(['pending'=>'Baru','processing'=>'Diproses','shipped'=>'Dikirim','completed'=>'Selesai','cancelled'=>'Dibatalkan'] as $k=>$v)<option value="{{ $k }}" @selected($status===$k)>{{ $v }}</option>@endforeach</select></label><button>Tampilkan</button>@if($search!=='' || $status)<a class="text-link" href="/manage/orders">Hapus filter</a>@endif</form>@endif
@if($staff && $search!=='')<p class="muted">{{ $orders->total() }} transaksi ditemukan untuk “{{ $search }}”.</p>@endif
<div class="panel table-wrap"><table><thead><tr><th>Nomor pesanan</th><th>Tanggal</th><th>Pelanggan</th><th>Total</th><th>Pembayaran</th><th>Sisa tagihan</th><th>Status pekerjaan</th><th></th></tr></thead><tbody>@forelse($orders as $order)<tr><td><strong>{{ $order->number }}</strong></td><td>{{ $order->created_at->format('d M Y') }}</td><td>{{ $order->customer_name }}</td><td>@rupiah($order->total)</td><td>{{ $order->status==='cancelled'?'Dibatalkan':($order->balance===0?'Lunas':'Belum lunas / DP') }}</td><td>@rupiah($order->status==='cancelled'?0:$order->balance)</td><td>@include('orders.status',['status'=>$order->status])</td><td><a class="text-link" href="/orders/{{ $order->id }}">Detail ↗</a></td></tr>@empty<tr><td colspan="8" class="empty">{{ $staff && $search!==''?'Tidak ada transaksi yang cocok.':'Belum ada pesanan untuk ditampilkan.' }}</td></tr>@endforelse</tbody></table>@include('components.pager',['paginator'=>$orders])</div>
@endsection

