@extends('layout')
@section('title','Detail pesanan')
@section('content')
<div class="page-heading"><div><span class="eyebrow">DETAIL TRANSAKSI</span><h1>{{ $order->number }}</h1><p>{{ $order->created_at->format('d M Y, H:i') }} · {{ ['cash'=>'Tunai di toko','transfer'=>'Transfer','cod'=>'Bayar saat diterima (COD)'][$order->payment_method]??$order->payment_method }}</p></div>@include('orders.status',['status'=>$order->status])</div>
<div class="split-layout"><section class="panel table-wrap"><h2>Produk yang dipesan</h2><table><thead><tr><th>Produk</th><th>Jumlah</th><th>Harga satuan</th><th>Subtotal</th>@can('owner')<th>Modal / biaya</th>@endcan</tr></thead><tbody>@foreach($order->items as $i)<tr><td>{{ $i->product_name }}<small>{{ $i->item_type==='service'?'Jasa servis':'Produk' }}</small></td><td>{{ $i->quantity }}</td><td>@rupiah($i->unit_price)</td><td>@rupiah($i->quantity*$i->unit_price)</td>@can('owner')<td>@if($i->cost_confirmed)@rupiah($i->unit_cost) / unit @else<span class="badge warning">Belum lengkap</span>@endif <a class="stock-sort-button" href="/manage/sale-items/{{ $i->id }}/cost">✎ Edit</a></td>@endcan</tr>@endforeach</tbody></table><div class="summary-line"><strong>Total pesanan</strong><strong>@rupiah($order->total)</strong></div>@can('owner')<div class="owner-info"><strong>Informasi Owner</strong>@if($order->items->contains(fn($item)=>!$item->cost_confirmed))<p class="badge warning">Modal belum lengkap — keuntungan sementara</p>@endif<p>Modal barang: @rupiah($order->items->sum(fn($i)=>$i->quantity*$i->unit_cost))</p><p>Potensi laba kotor: @rupiah($order->total-$order->items->sum(fn($i)=>$i->quantity*$i->unit_cost))</p><small>Diakui dalam laporan setelah pesanan selesai.</small></div>@endcan</section><section class="panel"><h2>Informasi penerima</h2><h3>{{ $order->customer_name }}</h3>@if($order->phone)<p>{{ $order->phone }}</p>@endif @if($order->work_description)<h3>Deskripsi Pengerjaan</h3><p class="preserve-lines">{{ $order->work_description }}</p>@endif<p class="preserve-lines">{{ $order->address }}</p>
@if(auth()->user()->isStaff() && !$order->staged_sale)
@php($transitions=['pending'=>['processing'=>'Proses pesanan','cancelled'=>'Batalkan pesanan'],'processing'=>['shipped'=>'Tandai dikirim','cancelled'=>'Batalkan pesanan'],'shipped'=>['completed'=>'Selesai & pembayaran diterima']])
@if(isset($transitions[$order->status]))<hr><form method="post" action="/manage/orders/{{ $order->id }}/status">@csrf @method('PUT')<label>Perbarui pesanan<select name="status">@foreach($transitions[$order->status] as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></label><button class="full">Simpan status</button></form><p class="muted">Pembatalan mengembalikan stok. Tandai selesai setelah barang dan pembayaran diterima.</p>@endif
@endif
</section></div>
@if($order->staged_sale)@include('orders.staged')@endif
@endsection

